from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import resic

class Ui_MainTry(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(695, 752)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(5, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setStyleSheet("QGroupBox{background-color:rgba(243,246,251,200);border-radius:10px;}")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setStyleSheet("QGroupBox{background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.661692 rgba(176, 196, 222, 255), stop:1 rgba(255, 255, 255, 255));border-bottom-right-radius:0px;border-bottom-left-radius:0px;}\n"
"QPushButton{border-radius:5px;padding:7px;}\n"
"QPushButton:hover{background-color:rgba(243,246,251,255);}\n"
"QPushButton:pressed{background-color:rgba(176,196,222,250);}\n"
"QLabel{color:rgba(255,255,255,255);}\n"
"")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.avatar_label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.avatar_label.sizePolicy().hasHeightForWidth())
        self.avatar_label.setSizePolicy(sizePolicy)
        self.avatar_label.setText("")
        self.avatar_label.setPixmap(QtGui.QPixmap(":/images/user1.png"))
        self.avatar_label.setObjectName("avatar_label")
        self.horizontalLayout_2.addWidget(self.avatar_label)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 9, -1, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.name_label = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.verticalLayout_3.addWidget(self.name_label)
        self.online = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.online.sizePolicy().hasHeightForWidth())
        self.online.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.online.setFont(font)
        self.online.setStyleSheet("")
        self.online.setObjectName("online")
        self.verticalLayout_3.addWidget(self.online)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.end_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_pushButton.sizePolicy().hasHeightForWidth())
        self.end_pushButton.setSizePolicy(sizePolicy)
        self.end_pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.end_pushButton.setIcon(icon)
        self.end_pushButton.setIconSize(QtCore.QSize(25, 25))
        self.end_pushButton.setObjectName("end_pushButton")
        self.horizontalLayout_2.addWidget(self.end_pushButton)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet("QListWidget{border:0px;background-color:rgba(176,196,222,250);}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chatlistWidget = QtWidgets.QListWidget(self.groupBox_2)
        self.chatlistWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.chatlistWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.chatlistWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.chatlistWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.chatlistWidget.setObjectName("chatlistWidget")
        self.horizontalLayout_4.addWidget(self.chatlistWidget)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(9, -1, 9, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_3.setStyleSheet("QGroupBox{background-color:rgba(252,253,255,200);}\n"
"QLineEdit{border:1px solid rgba(216,217,220,200);border-radius:5px;}\n"
"QPushButton{border-radius:5px;padding:7px;}\n"
"QPushButton:hover{background-color:rgba(243,246,251,255);}\n"
"QPushButton:pressed{background-color:rgba(176,196,222,250);}\n"
"")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.image_pushButton.sizePolicy().hasHeightForWidth())
        self.image_pushButton.setSizePolicy(sizePolicy)
        self.image_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/bukle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.image_pushButton.setIcon(icon1)
        self.image_pushButton.setIconSize(QtCore.QSize(25, 25))
        self.image_pushButton.setObjectName("image_pushButton")
        self.horizontalLayout.addWidget(self.image_pushButton)
        self.sendtext_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.sendtext_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.sendtext_lineEdit.setText("")
        self.sendtext_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sendtext_lineEdit.setObjectName("sendtext_lineEdit")
        self.horizontalLayout.addWidget(self.sendtext_lineEdit)
        self.send_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.send_pushButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.send_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_pushButton.setIcon(icon2)
        self.send_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.send_pushButton.setObjectName("send_pushButton")
        self.horizontalLayout.addWidget(self.send_pushButton)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.reclineEdit = QtWidgets.QLineEdit(Dialog)
        self.reclineEdit.setObjectName("reclineEdit")
        self.verticalLayout.addWidget(self.reclineEdit)
        self.reclineEditImg = QtWidgets.QLineEdit(Dialog)
        self.reclineEditImg.setObjectName("reclineEditImg")
        self.verticalLayout.addWidget(self.reclineEditImg)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.name_label.setText(_translate("Dialog", "Your Name"))
        self.online.setText(_translate("Dialog", "Online"))
        self.sendtext_lineEdit.setPlaceholderText(_translate("Dialog", "Напишите сообщение..."))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_MainTry()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
